name: Semantic versioning

on:
  push:
    branches: ["main"]

jobs:
  bump-version:
    name: "Bump Version on default branch"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v5"
        with:
          ref: ${{ github.ref }}
      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          patch-wording: "fix,patch"
          minor-wording: "new,feat,minor"
          major-wording: "major"
